<?xml version="1.0" encoding="utf-8" standalone="yes" ?>
<classmodel version="2.0" name="a">
    <students>
        <student>
            <name>192.168.19.25</name>
            <address mac="04D9C8B6A615" IP="192.168.19.25" />
            <posThumb x="106" y="386" />
            <group id="0" leader="0" x="0" y="0" />
            <signIn state="0" id="0" />
            <platform id="1" />
        </student>
        <student>
            <name>192.168.19.35</name>
            <address mac="04D9C8B6ACE1" IP="192.168.19.34" />
            <posThumb x="394" y="292" />
            <group id="0" leader="0" x="0" y="0" />
            <signIn state="0" id="0" />
            <platform id="1" />
        </student>
        <student>
            <name>192.168.19.44</name>
            <address mac="04D9C8B6CB85" IP="192.168.19.44" />
            <posThumb x="490" y="198" />
            <group id="0" leader="0" x="0" y="0" />
            <signIn state="0" id="0" />
            <platform id="1" />
        </student>
        <student>
            <name>192.168.19.9</name>
            <address mac="04D9C8B6A71C" IP="192.168.19.9" />
            <posThumb x="106" y="574" />
            <group id="0" leader="0" x="0" y="0" />
            <signIn state="0" id="0" />
            <platform id="1" />
        </student>
        <student>
            <name>192.168.19.29</name>
            <address mac="04D9C8B6A719" IP="192.168.19.29" />
            <posThumb x="586" y="386" />
            <group id="0" leader="0" x="0" y="0" />
            <signIn state="0" id="0" />
            <platform id="1" />
        </student>
        <student>
            <name>192.168.19.53</name>
            <address mac="04D9C8B6CBED" IP="192.168.19.53" />
            <posThumb x="682" y="104" />
            <group id="0" leader="0" x="0" y="0" />
            <signIn state="0" id="0" />
            <platform id="1" />
        </student>
        <student>
            <name>192.168.19.12</name>
            <address mac="04D9C8B6A4EA" IP="192.168.19.12" />
            <posThumb x="490" y="574" />
            <group id="0" leader="0" x="0" y="0" />
            <signIn state="0" id="0" />
            <platform id="1" />
        </student>
        <student>
            <name>192.168.19.27</name>
            <address mac="04D9C8B6A716" IP="192.168.19.27" />
            <posThumb x="394" y="386" />
            <group id="0" leader="0" x="0" y="0" />
            <signIn state="0" id="0" />
            <platform id="1" />
        </student>
        <student>
            <name>192.168.19.19</name>
            <address mac="04D9C8B6CBC3" IP="192.168.19.19" />
            <posThumb x="394" y="480" />
            <group id="0" leader="0" x="0" y="0" />
            <signIn state="0" id="0" />
            <platform id="1" />
        </student>
        <student>
            <name>192.168.19.36</name>
            <address mac="04D9C8B6A41D" IP="192.168.19.35" />
            <posThumb x="490" y="292" />
            <group id="0" leader="0" x="0" y="0" />
            <signIn state="0" id="0" />
            <platform id="1" />
        </student>
        <student>
            <name>192.168.19.14</name>
            <address mac="04D9C8B6A70B" IP="192.168.19.14" />
            <posThumb x="682" y="574" />
            <group id="0" leader="0" x="0" y="0" />
            <signIn state="0" id="0" />
            <platform id="1" />
        </student>
        <student>
            <name>192.168.19.4</name>
            <address mac="04D9C8B6AE7A" IP="192.168.19.4" />
            <posThumb x="490" y="668" />
            <group id="0" leader="0" x="0" y="0" />
            <signIn state="0" id="0" />
            <platform id="1" />
        </student>
        <student>
            <name>192.168.19.21</name>
            <address mac="04D9C8B6A4A0" IP="192.168.19.21" />
            <posThumb x="586" y="480" />
            <group id="0" leader="0" x="0" y="0" />
            <signIn state="0" id="0" />
            <platform id="1" />
        </student>
        <student>
            <name>192.168.19.51</name>
            <address mac="04D9C8B6A259" IP="192.168.19.51" />
            <posThumb x="490" y="104" />
            <group id="0" leader="0" x="0" y="0" />
            <signIn state="0" id="0" />
            <platform id="1" />
        </student>
        <student>
            <name>192.168.19.37</name>
            <address mac="04D9C8B6ACE6" IP="192.168.19.37" />
            <posThumb x="586" y="292" />
            <group id="0" leader="0" x="0" y="0" />
            <signIn state="0" id="0" />
            <platform id="1" />
        </student>
        <student>
            <name>192.168.19.50</name>
            <address mac="04D9C8B6A4A7" IP="192.168.19.50" />
            <posThumb x="394" y="104" />
            <group id="0" leader="0" x="0" y="0" />
            <signIn state="0" id="0" />
            <platform id="1" />
        </student>
        <student>
            <name>192.168.19.55</name>
            <address mac="04D9C8B6CBC0" IP="192.168.19.55" />
            <posThumb x="874" y="104" />
            <group id="0" leader="0" x="0" y="0" />
            <signIn state="0" id="0" />
            <platform id="1" />
        </student>
        <student>
            <name>192.168.19.7</name>
            <address mac="04D9C8B6CB63" IP="192.168.19.7" />
            <posThumb x="778" y="668" />
            <group id="0" leader="0" x="0" y="0" />
            <signIn state="0" id="0" />
            <platform id="1" />
        </student>
        <student>
            <name>192.168.19.30</name>
            <address mac="04D9C8B6A4CD" IP="192.168.19.30" />
            <posThumb x="682" y="386" />
            <group id="0" leader="0" x="0" y="0" />
            <signIn state="0" id="0" />
            <platform id="1" />
        </student>
        <student>
            <name>192.168.19.26</name>
            <address mac="04D9C8B6A3F8" IP="192.168.19.26" />
            <posThumb x="202" y="386" />
            <group id="0" leader="0" x="0" y="0" />
            <signIn state="0" id="0" />
            <platform id="1" />
        </student>
        <student>
            <name>192.168.19.6</name>
            <address mac="04D9C8B6A280" IP="192.168.19.6" />
            <posThumb x="682" y="668" />
            <group id="0" leader="0" x="0" y="0" />
            <signIn state="0" id="0" />
            <platform id="1" />
        </student>
        <student>
            <name>192.168.19.45</name>
            <address mac="04D9C8B6CB8D" IP="192.168.19.45" />
            <posThumb x="586" y="198" />
            <group id="0" leader="0" x="0" y="0" />
            <signIn state="0" id="0" />
            <platform id="1" />
        </student>
        <student>
            <name>192.168.19.11</name>
            <address mac="04D9C8B6A4AC" IP="192.168.19.11" />
            <posThumb x="394" y="574" />
            <group id="0" leader="0" x="0" y="0" />
            <signIn state="0" id="0" />
            <platform id="1" />
        </student>
        <student>
            <name>192.168.19.38</name>
            <address mac="04D9C8B6A65E" IP="192.168.19.38" />
            <posThumb x="682" y="292" />
            <group id="0" leader="0" x="0" y="0" />
            <signIn state="0" id="0" />
            <platform id="1" />
        </student>
        <student>
            <name>192.168.19.46</name>
            <address mac="04D9C8B6A48E" IP="192.168.19.46" />
            <posThumb x="682" y="198" />
            <group id="0" leader="0" x="0" y="0" />
            <signIn state="0" id="0" />
            <platform id="1" />
        </student>
        <student>
            <name>192.168.19.13</name>
            <address mac="04D9C8B6ACFE" IP="192.168.19.13" />
            <posThumb x="586" y="574" />
            <group id="0" leader="0" x="0" y="0" />
            <signIn state="0" id="0" />
            <platform id="1" />
        </student>
        <student>
            <name>192.168.19.2</name>
            <address mac="04D9C8B6A737" IP="192.168.19.2" />
            <posThumb x="202" y="668" />
            <group id="0" leader="0" x="0" y="0" />
            <signIn state="0" id="0" />
            <platform id="1" />
        </student>
        <student>
            <name>192.168.19.17</name>
            <address mac="04D9C8B6A8B4" IP="192.168.19.17" />
            <posThumb x="106" y="480" />
            <group id="0" leader="0" x="0" y="0" />
            <signIn state="0" id="0" />
            <platform id="1" />
        </student>
        <student>
            <name>192.168.19.49</name>
            <address mac="04D9C8B6A262" IP="192.168.19.49" />
            <posThumb x="202" y="104" />
            <group id="0" leader="0" x="0" y="0" />
            <signIn state="0" id="0" />
            <platform id="1" />
        </student>
        <student>
            <name>192.168.19.28</name>
            <address mac="04D9C8B6A461" IP="192.168.19.28" />
            <posThumb x="490" y="386" />
            <group id="0" leader="0" x="0" y="0" />
            <signIn state="0" id="0" />
            <platform id="1" />
        </student>
        <student>
            <name>192.168.19.15</name>
            <address mac="04D9C8B6A423" IP="192.168.19.15" />
            <posThumb x="778" y="574" />
            <group id="0" leader="0" x="0" y="0" />
            <signIn state="0" id="0" />
            <platform id="1" />
        </student>
        <student>
            <name>192.168.19.18</name>
            <address mac="04D9C8B6A4A8" IP="192.168.19.18" />
            <posThumb x="202" y="480" />
            <group id="0" leader="0" x="0" y="0" />
            <signIn state="0" id="0" />
            <platform id="1" />
        </student>
        <student>
            <name>192.168.19.48</name>
            <address mac="04D9C8B6A28F" IP="192.168.19.48" />
            <posThumb x="874" y="198" />
            <group id="0" leader="0" x="0" y="0" />
            <signIn state="0" id="0" />
            <platform id="1" />
        </student>
        <student>
            <name>192.168.19.32</name>
            <address mac="04D9C8B76556" IP="192.168.19.32" />
            <posThumb x="874" y="386" />
            <group id="0" leader="0" x="0" y="0" />
            <signIn state="0" id="0" />
            <platform id="1" />
        </student>
        <student>
            <name>192.168.19.3</name>
            <address mac="04D9C8B6A736" IP="192.168.19.3" />
            <posThumb x="394" y="668" />
            <group id="0" leader="0" x="0" y="0" />
            <signIn state="0" id="0" />
            <platform id="1" />
        </student>
        <student>
            <name>192.168.19.24</name>
            <address mac="04D9C8B6CB82" IP="192.168.19.24" />
            <posThumb x="874" y="480" />
            <group id="0" leader="0" x="0" y="0" />
            <signIn state="0" id="0" />
            <platform id="1" />
        </student>
        <student>
            <name>192.168.19.10</name>
            <address mac="04D9C8B75EC0" IP="192.168.19.10" />
            <posThumb x="202" y="574" />
            <group id="0" leader="0" x="0" y="0" />
            <signIn state="0" id="0" />
            <platform id="1" />
        </student>
        <student>
            <name>192.168.19.39</name>
            <address mac="04D9C8B6A45E" IP="192.168.19.39" />
            <posThumb x="778" y="292" />
            <group id="0" leader="0" x="0" y="0" />
            <signIn state="0" id="0" />
            <platform id="1" />
        </student>
        <student>
            <name>192.168.19.33</name>
            <address mac="04D9C8B6A60C" IP="192.168.19.33" />
            <posThumb x="106" y="292" />
            <group id="0" leader="0" x="0" y="0" />
            <signIn state="0" id="0" />
            <platform id="1" />
        </student>
        <student>
            <name>192.168.19.5</name>
            <address mac="04D9C8B69CD1" IP="192.168.19.5" />
            <posThumb x="586" y="668" />
            <group id="0" leader="0" x="0" y="0" />
            <signIn state="0" id="0" />
            <platform id="1" />
        </student>
        <student>
            <name>192.168.19.23</name>
            <address mac="04D9C8B6ACE3" IP="192.168.19.23" />
            <posThumb x="778" y="480" />
            <group id="0" leader="0" x="0" y="0" />
            <signIn state="0" id="0" />
            <platform id="1" />
        </student>
        <student>
            <name>192.168.19.43</name>
            <address mac="04D9C8B6A4F6" IP="192.168.19.43" />
            <posThumb x="394" y="198" />
            <group id="0" leader="0" x="0" y="0" />
            <signIn state="0" id="0" />
            <platform id="1" />
        </student>
        <student>
            <name>192.168.19.47</name>
            <address mac="04D9C8B6A4F2" IP="192.168.19.47" />
            <posThumb x="778" y="198" />
            <group id="0" leader="0" x="0" y="0" />
            <signIn state="0" id="0" />
            <platform id="1" />
        </student>
        <student>
            <name>192.168.19.16</name>
            <address mac="04D9C8B6A4F0" IP="192.168.19.16" />
            <posThumb x="874" y="574" />
            <group id="0" leader="0" x="0" y="0" />
            <signIn state="0" id="0" />
            <platform id="1" />
        </student>
        <student>
            <name>192.168.19.41</name>
            <address mac="04D9C8B6A4B1" IP="192.168.19.41" />
            <posThumb x="106" y="198" />
            <group id="0" leader="0" x="0" y="0" />
            <signIn state="0" id="0" />
            <platform id="1" />
        </student>
        <student>
            <name>192.168.19.40</name>
            <address mac="04D9C8B6A40C" IP="192.168.19.40" />
            <posThumb x="874" y="292" />
            <group id="0" leader="0" x="0" y="0" />
            <signIn state="0" id="0" />
            <platform id="1" />
        </student>
        <student>
            <name>192.168.19.1</name>
            <address mac="04D9C8B6A4C7" IP="192.168.19.1" />
            <posThumb x="106" y="668" />
            <group id="0" leader="0" x="0" y="0" />
            <signIn state="0" id="0" />
            <platform id="1" />
        </student>
        <student>
            <name>192.168.19.42</name>
            <address mac="04D9C8B6A4B8" IP="192.168.19.42" />
            <posThumb x="202" y="198" />
            <group id="0" leader="0" x="0" y="0" />
            <signIn state="0" id="0" />
            <platform id="1" />
        </student>
        <student>
            <name>192.168.19.31</name>
            <address mac="04D9C8B6A402" IP="192.168.19.31" />
            <posThumb x="778" y="386" />
            <group id="0" leader="0" x="0" y="0" />
            <signIn state="0" id="0" />
            <platform id="1" />
        </student>
        <student>
            <name>192.168.19.34</name>
            <address mac="04D9C8B6ADAA" IP="192.168.19.36" />
            <posThumb x="202" y="292" />
            <group id="0" leader="0" x="0" y="0" />
            <signIn state="0" id="0" />
            <platform id="1" />
        </student>
        <student>
            <name>192.168.19.20</name>
            <address mac="04D9C8B6A4AF" IP="192.168.19.20" />
            <posThumb x="490" y="480" />
            <group id="0" leader="0" x="0" y="0" />
            <signIn state="0" id="0" />
            <platform id="1" />
        </student>
        <student>
            <name>192.168.19.22</name>
            <address mac="04D9C8B6A4C6" IP="192.168.19.22" />
            <posThumb x="682" y="480" />
            <group id="0" leader="0" x="0" y="0" />
            <signIn state="0" id="0" />
            <platform id="1" />
        </student>
        <student>
            <name>192.168.19.54</name>
            <address mac="04D9C8B6A606" IP="192.168.19.54" />
            <posThumb x="778" y="104" />
            <group id="0" leader="0" x="0" y="0" />
            <signIn state="0" id="0" />
            <platform id="1" />
        </student>
        <student>
            <name>192.168.19.52</name>
            <address mac="04D9C8B6A426" IP="192.168.19.52" />
            <posThumb x="586" y="104" />
            <group id="0" leader="0" x="0" y="0" />
            <signIn state="0" id="0" />
            <platform id="1" />
        </student>
        <student>
            <name>192.168.19.8</name>
            <address mac="04D9C8B6A4BF" IP="192.168.19.8" />
            <posThumb x="874" y="668" />
            <group id="0" leader="0" x="0" y="0" />
            <signIn state="0" id="0" />
            <platform id="1" />
        </student>
    </students>
    <groups>
        <group id="255" function_mask="-1" arrange="0" name="所有成员" cx="80" cy="60" />
    </groups>
    <signInInfos signInStrategy="0" signInSeqId="0" />
</classmodel>
